### ISSUE TITLE
detect checkbox is checked or not 

### ISSUE THREAD

**Issue by satya5561** [Sreekiranar/box_detection_opencv#2]
How we identify that check boz is checked or not .

**Comment by Sreekiranar** [comment]
Here are a few of my suggestions
Approach 1: 
The detected boxes can contain more than one contour if it's non-empty. 
Approach 2:
You can identify the number of white pixels inside the detected box and arrive at a threshold for whether it's checked it not.
Approach 3: If you have an advanced OCR, it would be able to detect the text inside the box and we can use that as well. If the characters are recognised as something else due to the surrounding boxes, then we can erase the detected boxes and pass through the OCR engine once again to see if it identifies the characters inside the box correctly.
It's all logic and rules. There are multiple ways to arrive at a solution. Feel free to share your solution in this chain. It will be beneficial for all of us.
Thanks :D

**Comment by Sreekiranar** [comment]
Approach 3 will be useful in situations where we need to detect the actual content inside the checkboxes rather than just identifying if it's empty on non-empty.
